//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c300_kitabxana.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books_to_Readers
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> ReaderId { get; set; }
        public Nullable<System.DateTime> Buydate { get; set; }
        public Nullable<System.DateTime> Returndate { get; set; }
    
        public virtual book book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
