//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c300_kitabxana.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libdb : DbContext
    {
        public libdb()
            : base("name=libdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<Books_to_Readers> Books_to_Readers { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
    }
}
